### ISSUE TITLE
Patch works successfully, Game.exe closes

### ISSUE THREAD

**Issue by lnkszo9** [ferib/D2R-Offline#9]
No game window is ever opened. Game.exe closes every time.

I've tried tweaking the delay before suspending the process, even added it in as an argument to test many different combinations to no avail.

Game.exe always seems to close itself after the process is resumed..

System details:
Win 10 Professional 64 bit

**Comment by CDune23** [comment]
I have exactly the same problem. Everything seems to work until game.exe opens for a few seconds and then immediately closed. I have tried other cracks too, all have exactly the same issue. The files are downloaded directly with the tool from the Blizzard servers, I really have no idea what the issue is.

**Comment by lnkszo9** [comment]
So this is what I did and it started working:

- Opened b.net client, waited for the client to recognise I had an install of D2R.
- Verified the install files with the b.net client.
- Then after that it worked

**Comment by CDune23** [comment]
> So this is what I did and it started working:
> 
> * Opened b.net client, waited for the client to recognise I had an install of D2R.
> * Verified the install files with the b.net client.
> * Then after that it worked

Alas, I tried this but no luck for me, still closes immediately.

**Comment by lnkszo9** [comment]
> > So this is what I did and it started working:
> > 
> > * Opened b.net client, waited for the client to recognise I had an install of D2R.
> > * Verified the install files with the b.net client.
> > * Then after that it worked
> 
> Alas, I tried this but no luck for me, still closes immediately.

Try reinstalling D2R via the BNetInstaller tool, when it completes and you get a notification asking you to run Blizzard Updater, click "No" until it dismisses. Then do the process I said above

**Comment by mfrklic** [comment]
Also I noticed if you have a bad saved character file it will crash at main menu. I tried to hex edit a character save and since I was not able to fix the checksum for it to load properly it crashes right away. In case anyone else is trying to import or edit characters and runs into this.

**Comment by ryancrunchi** [comment]
Same issue, I don't get a UAC asking you to run Blizzard Updater

**Comment by ssassassassa** [comment]
same here the b net launcher did not recognize d2r is installed

**Comment by CDune23** [comment]
Guys I fixed this issue finally by installing the just released NVIDIA drivers, suddenly the game started, unlike the three other drivers I tried before. Maybe they fixed it in this driver release.

**Comment by ryancrunchi** [comment]
I have updated graphics drivers. Still have issue. I have Blizzard splashscreen. I have Diablo 2 splashscreen. Then game exits.
The same happens with shalzuth repo

**Comment by arthurEspooner** [comment]
> 
> 
> Guys I fixed this issue finally by installing the just released NVIDIA drivers, suddenly the game started, unlike the three other drivers I tried before. Maybe they fixed it in this driver release.

i just want to confirm that this worked for me as well. i played quite a bit then messed with some patching. the patches i was playing with seemed to corrupt something, so i downloaded latest master and re-downloaded the game files. even after this, the game still would not launch. i was very stumped and didn't expect it to be related to drivers. i know this is closed, but i'm curious what happened here? @CDune23 do you think the newer version on bnet just required the latest drivers?
